= Theming with PrimeNG

:idprefix:
:idseparator: -
:primeng_theming: https://primeng.org/theming
:theme_overrides: https://onecx.github.io/docs/guides/current/angular/cookbook/theming.html#theme-overrides
:theme_overrides_details:

The goal of this document is to explain how are theming mechanisms, available in OneCX, adapted for PrimeNG components and their theming. After reading this document it should be clear how PrimeNG components styles are adapted for the OneCX theming. 

[#primeng-theming]
== PrimeNG Theming
In the version 19, PrimeNG introduced {primeng_theming}[theming mechanism based on design tokens]. All PrimeNG components are going to adapt to the appearance specified in the configuration for design tokens.

[#onecx-theming-with-primeng-theming]
=== OneCX Theming With PrimeNG Theming
With OneCX theming a suite of CSS variables is always available to ensure that UIs have common look and feel in a certain workspace. On theme change, those variables are used to update the preset of design tokens used by all PrimeNG components to reflect the theme changes in them as well.

[#theme-overrides]
=== Theme Overrides
OneCX theming integration with PrimeNG theming is based on some assumptions related to OneCX theme variable association to PrimeNG design token. Because of that, some tokens are affected by the theme variables and some are not. Because of this and the fact that each UI can have its own requirements related to PrimeNG component styles, theme overrides were introduced.

Explanation of theme overrides mechanism and an example can be found {theme_overrides}[here].

[#technical-details]
== Technical Details
In this section, the technical details on how OneCX theming integrates with PrimeNG theming is explained

[#onecx-default-preset]
=== OneCX Default Preset
Important files:

* link:../../libs/angular-utils/src/lib/theme/preset/custom-preset.ts[The custom OneCX preset]
* link:../../libs/angular-utils/src/lib/theme/preset/preset-variables.ts[Token values for custom OneCX preset]
** Contains default tokens values
** Contains onecx extended section
* link:../../libs/angular-utils/src/lib/theme/preset/default-theme-variables.ts[Default theme variables values]
** Contains default theme variables values

Custom OneCX preset is the base for OneCX that does not take the theme set for accessed workspace into consideration.

[#onecx-extend-section]
=== OneCX Extend Section
The OneCX custom preset contains the theme variables values as design tokens in the extended `onecx` object. This section as well contains all custom design tokens defined by OneCX like the `errorColor` token. Those tokens can be utilized as any other tokens:

* errorColor
** Design token usage - `{onecx.error.color}`
** CSS variable usage - `--p-onecx-error-color`
* contentBgColor
** Design token usage - `{onecx.content.bg.color}`
** CSS variable usage - `--p-onecx-content-bg-color`

[#theme-appliance]
=== Theme Appliance
In order to apply theme variables to the PrimeNG design tokens:

* theme has to be activated on the page
* link:../../libs/angular-utils/src/lib/theme/application-config.ts[provideThemeConfig] has to be provided in the Microfrontend or Remote Component providers

The `provideThemeConfig` provider is essential to setup PrimeNG and other functionalities that are required to integrate OneCX theming with PrimeNG theming.

[#theme-config-service]
==== Theme Config Service
One of the essential services is link:../../libs/angular-utils/src/lib/services/theme-config.service.ts[ThemeConfigService]. In theming context, every time theme changes, it is responsible for updating the OneCX custom preset with the theme variables and applying it.

ThemeConfigService utilizes link:../../libs/angular-utils/src/lib/theme/theme-config.ts[ThemeConfig] object to update the extended `onecx` section of design tokens and recreates the primary palette. 

// TODO: Link style isolation
Apart from this its also responsible for providing the link:../../libs/angular-utils/src/lib/services/custom-use-style.service.ts[CustomUseStyle] which is used for {}[style isolation] purposes.
