
= Theme Overrides

:idprefix:
:idseparator: -
:theme_overrides: https://onecx.github.io/docs/guides/current/angular/theming.html#theme-overrides
:custom_use_style_service: ../../libs/angular-utils/src/lib/services/custom-use-style.service.ts

The goal of this document is to explain theme overrides for PrimeNG design tokens available in OneCX and technical details behind them. After reading this document it should be clear how theme overrides are achieved and how to use them.

[#overview]
== Overview
Theme overrides is a mechanism available for applications, that need to integrate with OneCX, allowing to override default design token values constructed by OneCX.

[#when-to-use]
== When to use
This mechanism should be used to control display of PrimeNG components inside the application. Each distinct application has to provide the overrides.

[#how-to-use]
== How to use
Explanation of theme overrides mechanism and an example from the application side can be found {theme_overrides}[here].

[#technical-details]
== Technical details
link:{custom_use_style_service}[CustomUseStyle] is responsible for applying overrides. Every time any PrimeNG style sheet is created/updated it is making sure that overrides are present and that they are overwriting the default values.

On every PrimeNG style sheet update, link:{custom_use_style_service}[CustomUseStyle] checks if overrides were provided by its owner application. If that was the case, it makes sure that a style sheet with those overrides is present in the DOM and then makes sure that it's located *AFTER* any PrimeNG style sheet. Because of the CSS rules priority, the overrides will be applied prior to any PrimeNG CSS variables.
