[#add-angular-material-plugin]
=== Add Angular Material Webpack Plugin

In OneCX v6, applications using Angular Material must add an additional Webpack plugin.
This change is required after upgrading to Angular 19.

[NOTE]
This setup will be replaced by a OneCX-provided Webpack plugin in a future version.

==== Required Changes

. Import `ModifySourcePlugin` and `ReplaceOperation` from `modify-source-webpack-plugin`.
. Create a `modifyMaterialPlugin` instance with a rules array containing one rule object:
  * The rule must define a `test` function that returns `true` when `module.resource` exists and the resource path includes `@angular/material` or `@angular/cdk`.
  * The rule must include an `operations` array with a `ReplaceOperation` configured with:
    - scope: `all`
    - match pattern: `document\.createElement\(`
    - replacement: `document.createElementFromMaterial({"this": this, "arguments": Array.from(arguments)},`
. Add the `modifyMaterialPlugin` instance to the Webpack `plugins` array.


.Example webpack.config.js
[source,javascript]
----
const { ModifySourcePlugin, ReplaceOperation } = require('modify-source-webpack-plugin')

const modifyMaterialPlugin = new ModifySourcePlugin({
  rules: [
    {
      test: (module) => {
        return (
          module.resource &&
          (module.resource.includes('@angular/material') ||
            module.resource.includes('@angular/cdk'))
        )
      },
      operations: [
        new ReplaceOperation(
          'all',
          'document\\.createElement\\(',
          'document.createElementFromMaterial({"this": this, "arguments": Array.from(arguments)},'
        )
      ]
    }
  ]
})

module.exports = {
  ...webpackConfig,
  plugins: [...plugins, modifyMaterialPlugin]
}
----
