[#primeng-new-plugin]
=== Add required plugin to webpack config for PrimeNG
OneCX version 6 uses PrimeNG 19 and requires Apps to add the following configuration to the `webpack.config.js` file:

* Add `ModifySourcePlugin` and `ReplaceOperation` classes from `modify-source-webpack-plugin`
* Create a modified PrimeNG plugin with `ModifySourcePlugin` class
* Export modified PrimeNG plugin in module exports plugins array

.webpack.config.js
[source,js]
....
const { ModifySourcePlugin, ReplaceOperation } = require('modify-source-webpack-plugin')
...
const modifyPrimeNgPlugin = new ModifySourcePlugin({
  rules: [
    {
      test: (module) => {
        return module.resource && module.resource.includes('primeng')
      },
      operations: [
        new ReplaceOperation(
          'all',
          'document\\.createElement\\(([^)]+)\\)',
          'document.createElementFromPrimeNg({"this": this, "arguments": Array.from(arguments), element: $1})'
        ),
        new ReplaceOperation('all', 'Theme.setLoadedStyleName', '(function(_){})')
      ]
    }
  ]
})
module.exports = {
  ...webpackConfig,
  plugins: [...plugins, modifyPrimeNgPlugin]
}
....