= Migrate OneCX App from Angular 18 to Angular 19

:idprefix:
:idseparator: -

[#overview]
== Overview

This guide provides comprehensive step-by-step instructions for migrating OneCX applications from Angular 18 to Angular 19.
As part of upgrading to Angular 19, you must update your OneCX UI libraries to version 6. This library update is not a standalone migration but a required part of the Angular version upgrade process, as OneCX v6 libraries provide Angular 19 compatibility and include necessary breaking changes.

[#prerequisites]
== Prerequisites

Before starting this migration:

* Your OneCX application is currently running on Angular 18
* You have OneCX UI libraries v5.x installed  
* You have a working development environment

[#migration-steps-before-angular-19]
== Migration Steps before upgrading to Angular 19

To simplify the migration process, it is recommended to complete the following steps before upgrading to Angular 19:

include::remove-keycloak-auth.adoc[]
include::update-component-imports.adoc[]
include::switch-to-new-components.adoc[]
include::remove-portal-layout-styles.adoc[]
include::update-filtertype-value.adoc[]
include::update-configuration-service-usage.adoc[]
include::adjust-packages-in-webpack-config.adoc[]
include::adjust-standalone-mode.adoc[]
include::remove-add-initialize-module-guard.adoc[]
include::remove-menuservice.adoc[]
include::update-translations.adoc[]

After these steps are completed, it is recommended to build the application to ensure that there are no remaining issues before proceeding with the Angular 19 upgrade:

[source,bash]
----
ng build
----


[#migration-steps-after-angular-19]
== Migration Steps after upgrading to Angular 19

Once the previous steps are completed, **the application should be upgraded to Angular 19 and libs v6 should be installed**. After the version updates are completed, the remaining steps of the migration can be followed:

include::update-packages.adoc[]
include::remove-portal-core-module.adoc[]
include::update-base-url.adoc[]
include::update-theme-service.adoc[]
include::add-required-plugin-to-primeng.adoc[]
include::add-angular-material-plugin.adoc[]
include::provide-theme-config.adoc[]
