[#update-translations]
=== Update Translation Path Factories
In OneCX v6, Use `provideTranslationPathFromMeta` and `createTranslateLoader` from `@onecx/angular-utils` for translation setup.`translationPathFactory` and `remoteComponentTranslationPathFactory` are deprecated.

**Update Imports:**

* Remove `translationPathFactory` and related imports from `component.ts`.
* Add `provideTranslationPathFromMeta` from `@onecx-angular-utils` and update providers with translation paths.
* Add `provideTranslateServiceForRoot` from `@onecx-angular-utils` and update providers with `TranslateModuleConfig`.
* If needed, import `createTranslateLoader`, `AngularAcceleratorMissingTranslationHandler` from `@onecx-angular-utils`.
* If needed, import `MissingTranslationHandler` from `@ngx-translate/core`.

Before:
[source,typescript]
----
@NgModule({
    providers: [
        {
            provide: TRANSLATION_PATH,
            useFactory: (appStateService: AppStateService) => translationPathFactory('assets/i18n/')(appStateService),
            multi: true,
            deps: [AppStateService]
        },
        provideHttpClient(withInterceptorsFromDi())
    ]
})
----

After:
[source,typescript]
----
@NgModule({
    providers: [
        provideTranslationPathFromMeta(import.meta.url, 'assets/i18n/'),
        provideHttpClient(withInterceptorsFromDi())
    ]
})
----


**Example - replace translationPathFactory with provideTranslationPathFromMeta in providers:**

Before:
[source,typescript]
----
@NgModule({
    providers: [
        // ... other providers,
        {
            provide: TRANSLATION_PATH,
            useFactory: (appStateService: AppStateService) => translationPathFactory('assets/i18n/')(appStateService),
            multi: true,
            deps: [AppStateService]
        }
    ]
})
----

After:
[source,typescript]
----
@NgModule({
    providers: [
        // ... other providers,
        provideTranslationPathFromMeta(import.meta.url, 'assets/i18n/')
    ]
})
----


**Example - replace remoteComponentTranslationPathFactory with provideTranslationPathFromMeta in providers:**

Before:
[source,typescript]
----
bootstrapRemoteComponent(RemoteComponent, 'ocx-my-remote-component', environment.production, [
    // ... other providers
    {
        provide: TRANSLATION_PATH,
        useFactory: (remoteComponentConfig: ReplaySubject<RemoteComponentConfig>) =>
            remoteComponentTranslationPathFactory('assets/i18n/')(remoteComponentConfig),
        multi: true,
        deps: [REMOTE_COMPONENT_CONFIG]
    },
]);
----

After:
[source,typescript]
----
bootstrapRemoteComponent(RemoteComponent, 'ocx-my-remote-component', environment.production, [
    // ... other providers
    provideTranslationPathFromMeta(import.meta.url, 'assets/i18n/')
]);
----

=== Configure Translation Providers for Remote Components

In OneCX v6, For each Remote Component translation related providers are required to be defined in the bootstrap.ts instead of the component.ts file. For multiple locales and fallback translations, use `AngularAcceleratorMissingTranslationHandler`.

**Update Imports:**

* Remove `translationPathFactory` and related imports from `component.ts`.
* Add `provideTranslationPathFromMeta` from `@onecx-angular-utils` and update providers with translation paths.
* Add `provideTranslateServiceForRoot` from `@onecx-angular-utils` and update providers with `TranslateModuleConfig`.
* If needed, import `createTranslateLoader`, `AngularAcceleratorMissingTranslationHandler` from `@onecx-angular-utils`.
* If needed, import `MissingTranslationHandler` from `@ngx-translate/core`.

Before:
[source,typescript]
----
import { TRANSLATION_PATH, translationPathFactory } from '@onecx/angular-utils'
import { AppStateService } from '@onecx-angular-integration-interface'

@Component({
  selector: 'ocx-my-remote',
  templateUrl: './my-remote.component.html',
  providers: [
    {
      provide: TRANSLATION_PATH,
      useFactory: (appStateService: AppStateService) =>
        translationPathFactory('assets/i18n/')(appStateService),
      deps: [AppStateService],
      multi: true,
    },
  ]
})
export class MyRemoteComponent {}
----

After:
[source,typescript]
----
import { bootstrapRemoteComponent } from '@onecx/angular-webcomponents'
import { provideTranslationPathFromMeta, createTranslateLoader } from '@onecx/angular-utils'
import { MyRemoteComponent } from './lib/my-remote.component'
import { TranslateLoader } from '@ngx-translate/core'
import { provideTranslateServiceForRoot } from '@onecx/angular-utils'
import { MissingTranslationHandler } from '@ngx-translate/core'
import { AngularAcceleratorMissingTranslationHandler } from '@onecx/angular-utils'
import { HttpClient } from '@angular/common/http'

bootstrapRemoteComponent(
  MyRemoteComponent,
  'ocx-my-remote',
  environment.production,
  [
    { provide: REMOTE_COMPONENT_CONFIG, useValue: new ReplaySubject<RemoteComponentConfig>(1) },
    provideTranslationPathFromMeta(import.meta.url, 'assets/i18n/'),
    provideTranslateServiceForRoot({
        isolate: true,
        loader: {
        provide: TranslateLoader,
        useFactory: createTranslateLoader,
        deps: [HttpClient]        
      },
      // Optionally, add MissingTranslationHandler for logging and fallback
      missingTranslationHandler: {
          provide: MissingTranslationHandler,
          useClass: AngularAcceleratorMissingTranslationHandler
        }
    })
  ]
)
----

[TIP]
====
If you need to support multiple locales and fallback for missing translations, use `AngularAcceleratorMissingTranslationHandler` from `@onecx/angular-utils` as the `MissingTranslationHandler`. This handler logs missing translation keys and provides a fallback mechanism.
====