[#update-translations]
=== Update Translation Path Factories
In OneCX v6, `createTranslateLoader`, `createRemoteComponentAndMfeTranslateLoader`, and `createRemoteComponentTranslateLoader` were removed from @onecx/angular-accelerator. `createTranslateLoader` and `provideTranslationPathFromMeta` can be imported from @onecx/angular-utils.

**Update Imports:**

* Remove createTranslateLoader, createRemoteComponentAndMfeTranslateLoader, createRemoteComponentTranslateLoader, translationPathFactory and remoteComponentTranslationPathFactory imports from `@onecx/angular-accelerator`.
* Add `provideTranslationPathFromMeta` from `@onecx/angular-utils`
* Add `provideTranslateServiceForRoot` from `@onecx/angular-utils` and update providers with `TranslateModuleConfig` from '@onecx/angular-utils'.
* Add `TRANSLATION_PATH` from `@onecx/angular-utils`
* Add `AngularAcceleratorMissingTranslationHandler` from `@onecx/angular-utils`.
* Add `MissingTranslationHandler` from `@ngx-translate/core`.

[NOTE]
====
* Use provideTranslationPathFromMeta with `import.meta.url` as the first argument and the location of your application's i18n files as the second argument.

*Hint:* To ensure the correct file path is used for import.meta.url, add the following to your application's webpack.config.js:

[source, typescript]
----
module.exports = {
 ...
  module: { parser: { javascript: { importMeta: false } } }
}
----
====

**Example - replace translationPathFactory with provideTranslationPathFromMeta in providers:**

.Before:
[source, typescript]
----
@NgModule({
    providers: [
        // ... other providers,
        {
            provide: TRANSLATION_PATH,
            useFactory: (appStateService: AppStateService) => translationPathFactory('assets/i18n/')(appStateService),
            multi: true,
            deps: [AppStateService]
        }
    ]
})
----

.After:
[source, typescript]
----
@NgModule({
    providers: [
        // ... other providers,
        provideTranslationPathFromMeta(import.meta.url, 'assets/i18n/')
    ]
})
----


**Example - replace remoteComponentTranslationPathFactory with provideTranslationPathFromMeta in providers:**

.Before:
[source, typescript]
----
bootstrapRemoteComponent(RemoteComponent, 'ocx-my-remote-component', environment.production, [
    // ... other providers
    {
        provide: TRANSLATION_PATH,
        useFactory: (remoteComponentConfig: ReplaySubject<RemoteComponentConfig>) =>
            remoteComponentTranslationPathFactory('assets/i18n/')(remoteComponentConfig),
        multi: true,
        deps: [REMOTE_COMPONENT_CONFIG]
    },
]);
----

.After:
[source, typescript]
----
bootstrapRemoteComponent(RemoteComponent, 'ocx-my-remote-component', environment.production, [
    // ... other providers
    provideTranslationPathFromMeta(import.meta.url, 'assets/i18n/')
]);
----

=== Configure Translation Providers for Remote Components

In OneCX v6, For each Remote Component translation related providers are required to be defined in the bootstrap.ts instead of the component.ts file. For multiple locales and fallback translations, use `AngularAcceleratorMissingTranslationHandler`.

**Update Imports:**

* Remove `translationPathFactory` and related imports from `component.ts`.
* Add `provideTranslationPathFromMeta` from `@onecx/angular-utils`
* Add `TRANSLATION_PATH` from `@onecx/angular-utils`
* Add `bootstrapRemoteComponent` from `@onecx/angular-webcomponents`
* Add `provideTranslationPathFromMeta`, `createTranslateLoader` from `@onecx/angular-utils`
* Add `provideTranslateServiceForRoot` from `@onecx/angular-utils`
* Add `MissingTranslationHandler` from `@ngx-translate/core`
* Add `AngularAcceleratorMissingTranslationHandler` from `@onecx/angular-utils`

[NOTE]
====
Use provideTranslationPathFromMeta with `import.meta.url` as the first argument and the location of your application's i18n files as the second argument.
====

.Before:
[source, typescript]
----
import { TRANSLATION_PATH, translationPathFactory } from '@onecx/angular-utils'
import { AppStateService } from '@onecx-angular-integration-interface'

@Component({
  selector: 'ocx-my-remote',
  templateUrl: './my-remote.component.html',
  providers: [
    {
      provide: TRANSLATION_PATH,
      useFactory: (appStateService: AppStateService) =>
        translationPathFactory('assets/i18n/')(appStateService),
      deps: [AppStateService],
      multi: true,
    },
  ]
})
export class MyRemoteComponent {}
----

.After:
[source, typescript]
----
bootstrapRemoteComponent(
  MyRemoteComponent,
  'ocx-my-remote',
  environment.production,
  [
    { provide: REMOTE_COMPONENT_CONFIG, useValue: new ReplaySubject<RemoteComponentConfig>(1) },
    provideTranslationPathFromMeta(import.meta.url, 'assets/i18n/'),
    provideTranslateServiceForRoot({
        isolate: true,
        loader: {
        provide: TranslateLoader,
        useFactory: createTranslateLoader,
        deps: [HttpClient]        
      },
      // Optionally, add MissingTranslationHandler for logging and fallback
      missingTranslationHandler: {
          provide: MissingTranslationHandler,
          useClass: AngularAcceleratorMissingTranslationHandler
        }
    })
  ]
)
----

[TIP]
====
If you need to support multiple locales and fallback for missing translations, use `AngularAcceleratorMissingTranslationHandler` from `@onecx/angular-utils` as the `MissingTranslationHandler`. This handler logs missing translation keys and provides a fallback mechanism.
====