:idprefix:
:idseparator: -
:page-toclevels: 4

:troubleshooting_shared_packages: xref:documentation:onecx-docs-dev:guides/troubleshooting.adoc#shell-related

[#onecx-compatibility]
= OneCX UI Libraries: Compatibility

This guide lists the minimal requirements for an UI App to be fully compatible with OneCX. Each requirement is classified as "must-have" or "should-have" and the impact of missing each requirement is described.

[#general]
== General

[#general-must-have-requirements]
=== Must-have Requirements

[#application-exposal]
==== Application exposal
Application uses module federation exposing remoteEntry.js (any technology)::
Impact: Applications exposed with different technologies might not be compatible with the Shell
+
* Ensure your App exposes remoteEntry.js and is configured for module federation.

[#asset-exposal]
==== Asset exposal
Expose assets of used libraries::
Impact: Translations missing
+
* Confirm assets (e.g., i18n) from libraries are exposed and available in your build output.
* Include the assets of the libraries they use in the angular.json or project.json file.

.Example assets configuration
[source,json]
----
...
  "build": {
    ...
    "assets": [
      ...
      // @onecx/portal-integration-angular
      {
        "glob": "**/*",
        "input": "node_modules/@onecx/portal-integration-angular/assets/",
        "output": "/onecx-portal-lib/assets/"
      }
      // @onecx/angular-accelerator
      {
        "glob": "**/*",
        "input": "./node_modules/@onecx/angular-accelerator/assets/",
        "output": "/onecx-angular-accelerator/assets/"
      }
      // @onecx/angular-utils
      {
        "glob": "**/*",
        "input": "./node_modules/@onecx/angular-utils/assets/",
        "output": "/onecx-angular-utils/assets/"
      }
      ...
    ],
    ...
  }
...
----

[#style-exposal]
==== Styles exposal
Expose styles.css of used libraries::
Impact: Styles of components from libraries might be incorrect
+
* Expose library styles in project.json or angular.json.

.Example styles configuration
[source,json]
----
...
  "build": {
    ...
    "styles": [
      ...
      // @onecx/portal-integration-angular
      "node_modules/@onecx/portal-integration-angular/assets/styles.scss",
      
      // @onecx/angular-accelerator
      "node_modules/@onecx/angular-accelerator/assets/styles.scss",
      ...
    ],
    ...
  }
...
----

[#package-sharing]
==== Package sharing
Sharing is done with '^' sign to allow version flexibility::
Impact: We should share as much as possible
+
* Use caret '^' for all shared package versions in package.json (except rxjs, which should use '~').
* Especially important for Angular packages to avoid trying to use multiple versions of Angular in the same environment, which is not allowed.

// TODO: Add link to OneCX sharing utilities guide
All required packages are shared::
Impact: Broken application
+
* Share all required packages
** @angular/*
** @ngx-translate/*
** @onecx/*
** rxjs
** primeng
* Its recommended to use the OneCX utilities to share packages. For more information, please refer to the xref:TODO[OneCX Utilities Guide].

Share @onecx/angular-utils library::
Impact: Might lead to unwanted side effects for your App and also other Apps in the Shell.
+
* Must be done if *@onecx/angular-accelerator* or *@onecx/portal-integration-interface* is used and shared.
* Please check your configuration and make sure to include the @onecx/angular-utils in the shared modules or dependencies.

[#allow-import-meta]
==== Allow importMeta in configuration
importMeta is configured::
Impact: Translation issues
+
* Ensure your configuration includes the correct importMeta configuration.
* For the correct configuration, please refer to the xref:documentation:docs-guides-ui:angular/translation/multi-language-setup.adoc#provide-translation-path[OneCX Multi-language Translations Guide] and other information on multi-language in OneCX.

[#general-should-have-requirements]
=== Should-have Requirements

[#expose-app-styles]
==== Expose App styles.css
Impact: No styles for the application are loaded
+
* Ensure your App exposes its styles.css.
* How the styles.css is exposed depends on the package used for building the App (NX or Angular CLI).
* NX:

.project.json
[source,json]
----
{
    ...
    "styles": [
        {
            "input": "./src/styles.scss",
            "bundleName": "styles",
            "inject": true
        }
    ],
    ...
}
----

* Angular CLI:

.package.json
[source,json]
----
{
  ...
  "scripts": {
    "postbuild": "mv \"$(find dist/my-project-name -maxdepth 1 -type f -name 'styles.*.css' | head -n 1)\" dist/my-project-name/styles.css",
  }
  ...
}
----

* Adjust the build command in package.json to rename the generated styles file to styles.css because of the hash in the filename by adding
`cp dist/replace_path_to/styles.*.css dist/replace_path_to/styles.css"`
* Ensure the styles.css including all your styles is present in the build output.

.Example package.json
[source,json]
----
{
  ...
  "scripts": {
    ...
    "build": "nx build && cp dist/my-project-name/styles.*.css dist/my-project-name/styles.css",
    ...
  }
  ...
}
----

[#angular]
== Angular

[#angular-must-have-requirements]
=== Must-have Requirements

[#angular-version-compatibility]
==== Angular version compatibility
Angular package version has to be lower than the Shell::
Impact: Broken environment
+
* Check the Shell version and ensure your App uses an equal or lower Angular version.
* Please refer to the {troubleshooting_shared_packages}[Troubleshooting Guide] to know what versions are available in the environment.

[#application-bootstrap]
==== Application bootstrap
Application is constructed using @onecx/angular-webcomponents::
Impact: Router out of sync, many potential issues
+
* For step-by-step instructions on migrating a vanilla Angular App to a OneCX-compatible microfrontend using @onecx/angular-webcomponents among other packages, refer to the xref:documentation:docs-guides-ui:angular/app-to-onecx.adoc#migration-steps[Migration Steps in Vanilla to OneCX Migration Guide].

[#routing-with-relative-paths]
==== Routing with relative paths
Routing is done with relative paths::
Impact: Incorrect routing results
+
* Use relative paths in Angular router configuration to avoid navigation issues.
* Please refer to the xref:documentation:docs-guides-ui:angular/routing/index.adoc#general-routing-guidelines[OneCX Routing Guide] for using relative paths and other information on routing in OneCX.

[#angular-compatibility]
==== Angular compatibility
Ensure package compatibility::
Impact: Broken application
+
* Verify that all packages used in your App are compatible with OneCX.


.Compatible package versions for Angular 18
|===
| Package               | Compatible Versions
| @onecx/*              | ^5.0.0
| @ngx-translate/core   | ^15.0.0
| ngx-build-plus        | ^18.0.0
| primeng               | ^17.18.0
|===

.Compatible package versions for Angular 19
|===
| Package                        | Compatible Versions
| @onecx/*              | ^6.0.0
| @ngx-translate/core   | ^16.0.0
| ngx-build-plus        | ^19.0.0
| primeng               | ^19.0.0
|===

.Compatible package versions for Angular 20
|===
| Package                        | Compatible Versions
| @onecx/*              | ^7.0.0
| @ngx-translate/core   | ^17.0.0
| ngx-build-plus        | ^20.0.0
| primeng               | ^20.0.0
|===

.Compatible package versions for Angular 21
|===
| Package                        | Compatible Versions
| @onecx/*              | ^8.0.0
| @ngx-translate/core   | ^17.0.0
| ngx-build-plus        | ^21.0.0
| primeng               | ^21.0.0
|===
