name: 'setup-environment'
description: 'Setup Node.js, install dependencies'
inputs:
  node:
    description: 'Node version'
    default: '20'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node }}
        cache: 'npm'

    - name: Set SHAs for affected commands
      uses: nrwl/nx-set-shas@v4
    - name: Show npm registry
      run: npm config get registry
      shell: bash
    - name: Install deps
      run: npm ci
      shell: bash
