= Target Picture - OneCX Storybooks

The goal of this document is to establish the vision for Storybooks within the OneCX context. It outlines the purpose of our Storybooks, along with the expected structure. Additionally, it defines the key documentation and overview pages that should be included, specifies which components should be covered by stories, and details the number of stories required to ensure a sufficient coverage.

[#purpose]
== Purpose of Storybooks in OneCX

Storybooks in OneCX should be seen as the primary resource and single source of truth for all information regarding OneCX libraries and components. The target audience includes both members of the OneCX core team, as well as external developers who are using OneCX in their projects. 

To achieve this goal and ensure that our Storybooks are a valuable resource, it's crucial to not only document individual components, but also to provide a comprehensive overview of the entire OneCX ecosystem, its individual libraries, the relationships between them and recent changes that have been applied to them.

After looking at the OneCX Storybooks, developers should have a clear understanding of what OneCX is and how they can utilize it in their projects.

[#structure]
== Expected Structure of Storybooks in OneCX

Based on the purpose outlined above, the following ideal structure for OneCX Storybooks can be derived:

There should be one top-level Storybook for all of OneCX. This Storybook should explain what OneCX is, where developers can report bugs or submit feature requests and how they can contribute to the project. Additionally it should contain a subfolder for migration guides (e.g. v5 to v6) or link to the respective guide, should it exist in some other location (e.g. in OneCX Docs). In addition to the migration guides, the top-level Storybook should also link to all other external resources that might be relevant for developers using OneCX. This includes but isn't limited to links to the OneCX GitHub organization and the OneCX Docs. Lastly, it should list all @onecx libraries, briefly mention what their purpose is and link to their respective Storybooks. The library Storybooks should be added as child Storybooks inside the top-level Storybook. Child Storybooks can be added using xref:https://storybook.js.org/docs/sharing/storybook-composition[Storybook's composition feature].

Each lib-specific Storybook should be seen as the first entrypoint for developers wanting to work with a specific library. It should explain the respective library and its components in greater detail. The recommended structure for these Storybooks is as follows:

. Home page
* Name of library
* Purpose and main use cases of the library
* Description of the structure of the Storybook
* Link to the library's GitHub repository and other relevant external resources

. Versions folder 
* Contains one subfolder for each major version of the library
* Contents of subfolders should be pulled in from version-specific Storybooks using xref:https://storybook.js.org/docs/sharing/storybook-composition[Storybook's composition feature]

Each version-specific Storybook should contain the following sections:

. Summary page
* Describes the main differences between the given version and the previous one
* Allows developers to quickly understand the main reasons for upgrading to newer versions
. Changelog page
* Lists all changes that have been applied to the library in the given version
. Migration guide page
* Explains how to migrate from the previous version to the given one
. Installation/Getting started page
* Explains how to install and set up the library
. Library structure folder
* Contains a summary page explaining the structure of the library and how the components are organized
* Contains subfolders for each of the library's main components (e.g. components, directives, pipes, services, utils)
.. Components folder (if applicable)
... One folder for each component
.... Contains a top-level page explaining the component, its inputs/outputs and its purpose/use-cases -> should be written in xref:https://storybook.js.org/docs/6/writing-docs/docs-page#with-mdx-documentation[MDX]
.... Contains a kitchen sink story providing "controls" for all possible configuration options
*** Enables developers to play around with the component and find the configuration that fits their needs
.... Contains one story for each of the component's main use-cases (niche use-cases don't have to be covered as they are covered by the kitchen sink story)

.. Directives folder (if applicable)
... One folder or page for each directive
.... Contains a top-level page explaining the directive, usage options and its purpose/use-cases -> should be written in xref:https://storybook.js.org/docs/6/writing-docs/docs-page#with-mdx-documentation[MDX]
.... (Optional) Contains stories showing the directive in action (e.g. applied to different components and using different configurations)

.. Pipes folder (if applicable)
... One folder or page for each pipe
.... Contains a top-level page explaining the pipe and its purpose/use-cases -> should be written in xref:https://storybook.js.org/docs/6/writing-docs/docs-page#with-mdx-documentation[MDX]
.... Contains story/stories showing the pipe in action (e.g. applied to a string)
.. Services folder (if applicable)
... (Optional) Contains folders grouping services by their purpose
... One page for each service explaining the service and its purpose/use-cases
.. Utils folder (if applicable)
... (Optional) Contains folders grouping utility functions by their purpose
... One page for each utility function explaining the function and its purpose/use-cases
. Other topics folder (e.g. Theming, Templating, etc.)
* Contains pages explaining other important topics related to the library

One example for a well-structured Storybook containing most of the elements mentioned above is the documentation of the open source library xref:https://circuit.sumup.com/?path=/docs/introduction-welcome--docs[Circuit UI by SumUp]

