import type { CssRule } from '../../mapper.types'

export const pageHeaderCssRules: CssRule[] = [
  {
    selector: '.onecx-page-header',
    declarations: [
      { property: 'background-color', from: 'usages.pageHeader.background.color' },
      { property: 'border-color', from: 'usages.pageHeader.border.color' },
      { property: 'border-width', from: 'usages.pageHeader.border.width' },
      { property: 'border-radius', from: 'usages.pageHeader.border.radius' },
      { property: 'box-shadow', from: 'usages.pageHeader.border.shadow' },
      { property: 'padding-left', from: 'usages.pageHeader.paddingX' },
      { property: 'padding-right', from: 'usages.pageHeader.paddingX' },
      { property: 'padding-top', from: 'usages.pageHeader.paddingY' },
      { property: 'padding-bottom', from: 'usages.pageHeader.paddingY' },
      { property: 'margin-left', from: 'usages.pageHeader.marginX' },
      { property: 'margin-right', from: 'usages.pageHeader.marginX' },
      { property: 'margin-top', from: 'usages.pageHeader.marginY' },
      { property: 'margin-bottom', from: 'usages.pageHeader.marginY' },
    ],
  },
  {
    selector: '.onecx-page-header .title-bar',
    declarations: [
      { property: 'color', from: 'usages.pageHeader.header.color' },
      { property: 'background-color', from: 'usages.pageHeader.header.background.color' },
      { property: 'padding-left', from: 'usages.pageHeader.header.paddingX' },
      { property: 'padding-right', from: 'usages.pageHeader.header.paddingX' },
      { property: 'padding-top', from: 'usages.pageHeader.header.paddingY' },
      { property: 'padding-bottom', from: 'usages.pageHeader.header.paddingY' },
      { property: 'gap', from: 'usages.pageHeader.header.gap' },
    ],
  },
  {
    selector: '.onecx-page-header .title-wrap',
    declarations: [{ property: 'align-items', from: 'usages.pageHeader.header.titleWrap.alignItems' }],
  },
  {
    selector: '.onecx-page-header #page-header',
    declarations: [
      { property: 'font-family', from: 'usages.pageHeader.header.title.font.family' },
      { property: 'font-size', from: 'usages.pageHeader.header.title.font.size' },
      { property: 'font-weight', from: 'usages.pageHeader.header.title.font.weight' },
      { property: 'padding-left', from: 'usages.pageHeader.header.title.paddingX' },
      { property: 'padding-right', from: 'usages.pageHeader.header.title.paddingX' },
      { property: 'padding-top', from: 'usages.pageHeader.header.title.paddingY' },
      { property: 'padding-bottom', from: 'usages.pageHeader.header.title.paddingY' },
    ],
  },
  {
    selector: '.onecx-page-header #page-subheader',
    declarations: [
      { property: 'font-family', from: 'usages.pageHeader.header.subtitle.font.family' },
      { property: 'font-size', from: 'usages.pageHeader.header.subtitle.font.size' },
      { property: 'font-weight', from: 'usages.pageHeader.header.subtitle.font.weight' },
      { property: 'padding-left', from: 'usages.pageHeader.header.subtitle.paddingX' },
      { property: 'padding-right', from: 'usages.pageHeader.header.subtitle.paddingX' },
      { property: 'padding-top', from: 'usages.pageHeader.header.subtitle.paddingY' },
      { property: 'padding-bottom', from: 'usages.pageHeader.header.subtitle.paddingY' },
    ],
  },
  {
    selector: '.onecx-page-header .figure .colorblob',
    declarations: [{ property: 'background-color', from: 'usages.pageHeader.header.titleIcon.background.color' }],
  },
  {
    selector: '.onecx-page-header .figure .figure-image img',
    declarations: [
      { property: 'width', from: 'usages.pageHeader.header.titleIcon.image.width' },
      { property: 'height', from: 'usages.pageHeader.header.titleIcon.image.height' },
    ],
  },
  {
    selector: '.onecx-page-header .action-items-wrap',
    declarations: [
      { property: 'padding-left', from: 'usages.pageHeader.header.actionPanel.paddingX' },
      { property: 'padding-right', from: 'usages.pageHeader.header.actionPanel.paddingX' },
      { property: 'padding-top', from: 'usages.pageHeader.header.actionPanel.paddingY' },
      { property: 'padding-bottom', from: 'usages.pageHeader.header.actionPanel.paddingY' },
      { property: 'gap', from: 'usages.pageHeader.header.actionPanel.gap' },
    ],
  },
  {
    selector: '.onecx-page-header .object-panel',
    declarations: [
      { property: 'color', from: 'usages.pageHeader.content.color' },
      { property: 'background-color', from: 'usages.pageHeader.content.background.color' },
      { property: 'border-top-color', from: 'usages.pageHeader.content.border.top.color' },
      { property: 'border-top-width', from: 'usages.pageHeader.content.border.top.width' },
      { property: 'padding-left', from: 'usages.pageHeader.content.paddingX' },
      { property: 'padding-right', from: 'usages.pageHeader.content.paddingX' },
      { property: 'padding-top', from: 'usages.pageHeader.content.paddingY' },
      { property: 'padding-bottom', from: 'usages.pageHeader.content.paddingY' },
      { property: 'font-family', from: 'usages.pageHeader.content.font.family' },
      { property: 'font-size', from: 'usages.pageHeader.content.font.size' },
      { property: 'font-weight', from: 'usages.pageHeader.content.font.weight' },
    ],
  },
  {
    selector: '.onecx-page-header .object-detail-label',
    declarations: [
      { property: 'color', from: 'usages.pageHeader.content.label.color' },
      { property: 'padding-left', from: 'usages.pageHeader.content.label.paddingX' },
      { property: 'padding-right', from: 'usages.pageHeader.content.label.paddingX' },
      { property: 'padding-top', from: 'usages.pageHeader.content.label.paddingY' },
      { property: 'padding-bottom', from: 'usages.pageHeader.content.label.paddingY' },
      { property: 'gap', from: 'usages.pageHeader.content.label.gap' },
      { property: 'font-family', from: 'usages.pageHeader.content.label.font.family' },
      { property: 'font-size', from: 'usages.pageHeader.content.label.font.size' },
      { property: 'font-weight', from: 'usages.pageHeader.content.label.font.weight' },
    ],
  },
  {
    selector: '.onecx-page-header .object-detail-value',
    declarations: [
      { property: 'color', from: 'usages.pageHeader.content.value.color' },
      { property: 'padding-left', from: 'usages.pageHeader.content.value.paddingX' },
      { property: 'padding-right', from: 'usages.pageHeader.content.value.paddingX' },
      { property: 'padding-top', from: 'usages.pageHeader.content.value.paddingY' },
      { property: 'padding-bottom', from: 'usages.pageHeader.content.value.paddingY' },
      { property: 'font-family', from: 'usages.pageHeader.content.value.font.family' },
      { property: 'font-size', from: 'usages.pageHeader.content.value.font.size' },
      { property: 'font-weight', from: 'usages.pageHeader.content.value.font.weight' },
    ],
  },
  {
    selector: '.onecx-page-header .object-info-grid-value .object-detail-icon',
    declarations: [{ property: 'color', from: 'usages.pageHeader.content.value.color' }],
  },
  {
    selector: '.onecx-page-header .object-detail-label',
    declarations: [
      { property: 'color', from: 'usages.pageHeader.content.label.color' },
      { property: 'padding-left', from: 'usages.pageHeader.content.label.paddingX' },
      { property: 'padding-right', from: 'usages.pageHeader.content.label.paddingX' },
      { property: 'padding-top', from: 'usages.pageHeader.content.label.paddingY' },
      { property: 'padding-bottom', from: 'usages.pageHeader.content.label.paddingY' },
      { property: 'gap', from: 'usages.pageHeader.content.label.gap' },
      { property: 'font-family', from: 'usages.pageHeader.content.label.font.family' },
      { property: 'font-size', from: 'usages.pageHeader.content.label.font.size' },
      { property: 'font-weight', from: 'usages.pageHeader.content.label.font.weight' },
    ],
  },
  {
    selector: '.onecx-page-header .object-detail-value',
    declarations: [
      { property: 'color', from: 'usages.pageHeader.content.value.color' },
      { property: 'padding-left', from: 'usages.pageHeader.content.value.paddingX' },
      { property: 'padding-right', from: 'usages.pageHeader.content.value.paddingX' },
      { property: 'padding-top', from: 'usages.pageHeader.content.value.paddingY' },
      { property: 'padding-bottom', from: 'usages.pageHeader.content.value.paddingY' },
      { property: 'font-family', from: 'usages.pageHeader.content.value.font.family' },
      { property: 'font-size', from: 'usages.pageHeader.content.value.font.size' },
      { property: 'font-weight', from: 'usages.pageHeader.content.value.font.weight' },
    ],
  },
  {
    selector: '.onecx-page-header .object-detail-value .object-detail-icon',
    declarations: [{ property: 'color', from: 'usages.pageHeader.content.value.color' }],
  },
]
