/**
 * 1000kit APM permission api
 * API for permission and application management
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Permission {
  /**
   * Domain resource that this permissions is applied to
   */
  resource?: string
  /**
   * Action invocable on the domain resource that this permissions is applied to
   */
  action?: string
  /**
   * Permission identifier in form RESOURCE#ACTION
   */
  key?: string

  name?: string
}
