/**
 * 1000kit internal api
 * API for portal
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserPerson {
  firstName?: string
  lastName?: string
  displayName?: string
  email?: string
  address?: UserPersonAddress
  phone?: UserPersonPhone
}

export interface UserPersonAddress {
  street?: string
  streetNo?: string
  city?: string
  postalCode?: string
  country?: string
}

export interface UserPersonPhone {
  type?: PhoneType
  number?: string
}

export enum PhoneType {
  MOBILE = 'MOBILE',
  LANDLINE = 'LANDLINE',
}
