export * from './lib/model/remote-component'
export * from './lib/model/remote-component-config.model'
export * from './lib/model/injection-tokens'
export * from './lib/components/slot/slot.component'
export * from './lib/angular-remote-components.module'
export * from './lib/services/slot.service'
export * from './lib/utils/provide-translate-service-for-root.utils'