= Documentation Creation Guidelines
This document provides a step-by-step guide on how to create documentation for Angular components in Storybook, highlighting multipile ways of documentation creation.

== Introduction
Storybook automatically creates documentation due to the tag `tags:['autodocs]` in the `angular-accelerator/.storybook/preview.ts` file. This can be disabled in the stories e.g.
`your-component.component.stories.ts` (see, https://storybook.js.org/docs/writing-docs/autodocs#set-up-automated-documentation)

[source, JavaScript]
----
export default {
title: 'Components/YourComponent',
component: YourComponent,
tags:['!autodocs'],
...
}
----

To recognize MDX files, the attribute `stories` in `angular-accelerator/.storybook/main.ts` must be extended by the line `../src/**/*.mdx` (see, https://storybook.js.org/docs/writing-docs/mdx#setup-custom-documentation).
[source, JavaScript]
----
module.exports = {
  ...rootMain,
  staticDirs: [{ from: '../assets', to: '/assets' }],
  stories: [
    '../src/**/*.mdx',
    '../src/lib/**/*.stories.@(js|jsx|ts|tsx)'
  ]
}
----

Now MDX files can be recognized in the folder structure.

== JSDoc Comments

JSDoc comments are a powerful way to add detailed descriptions to your stories, which can be automatically included in your Storybook documentation. These comments are placed directly above the story element they describe.

=== Writing JSDoc Comments

To write JSDoc comments, use the `/** */` notation. Here is an example (see, https://storybook.js.org/docs/api/doc-blocks/doc-block-description#description):

`your-component.component.storie.ts`
[source, JavaScript]
----
/**
* Description of your Story
*/
export const YourStorie = {
  render: Template,

  args: {
    diagramType: YourComponent.Example,
    data: mockData,
  },
}
----

=== Why using JSDoc?
Using JSDoc comments offers several advantages. One of the key benefits is the ability to easily display these comments in your documentation using the <Description /> block. This integration allows you to automatically pull detailed descriptions directly from your code, ensuring that your documentation is always up-to-date and accurately reflects the latest changes.


== MDX Files in Storybook

=== How to Create a Document with MDX

MDX files combine Markdown and JSX to create interactive documentation. Here are the steps to create an MDX document:

. *Create an MDX File*: Create a new file with the `.mdx` extension in your project directory.
. *Import the Required Blocks*: Import the https://storybook.js.org/docs/writing-docs/doc-blocks#available-blocks[Storybook blocks] you want to use.

[source, JavaScript]
----
import { Meta, Story, Primary, Controls, Title, Stories, Canvas } from '@storybook/blocks';

import * as YourComponentStories from './your-component.component.stories.ts';

<Meta of={YourComponentStories} />
<Title />
<Description />
<Primary />
<Controls />
<Stories />
----

*Add Markdown Content*: You can add regular Markdown text to complement your documentation.

[source, Markdown]
----
# Your Component
This is a description of your component.
----

=== How to Replace Autodocs with an MDX File

To replace an Autodocs page with an MDX file, you have two options:

*Disable Autodocs for the Specific Component*: Remove the autodocs tag in the story file.

[source, JavaScript]
----
export default {
  title: 'Components/YourComponent',
  component: YourComponent,
  tags: ['!autodocs'],
  ...
}
----

*Create an MDX File for the Documentation*: Create a new .mdx file and import the required blocks. It is *important* that the title in the Meta tag is the name of the component to be replaced.

[source, JavaScript]
----
import { Meta, Story, Primary, Controls, Title, Stories, Canvas } from '@storybook/blocks';

import * as YourComponentStories from './your-component.component.stories.ts';

<Meta title='Components/YourComponent' />

<Title of={YourComponentStories} />
<Primary of={YourComponentStories.default} />
<Controls of={YourComponentStories.default} />
<Canvas of={YourComponentStories.YourComponentSecondary} />
----

=== When Does It Make Sense to Disable Autodocs and When to Overwrite Them?

Disable Autodocs:

* *Customization Needs*: When you need specific, customized documentation that goes beyond the automatically generated one.
* *Complex Components*: For complex components that require detailed explanations and examples that cannot be automatically generated.

Use Autodocs:

* *Enhanced Documentation*: When you want to provide more detailed and tailored documentation for your components.
* *Specific Use Cases*: For components with unique use cases that require specific documentation not covered by autodocs.

Autodocs are useful for quickly and consistently creating documentation, while MDX files offer more flexibility and customization options.

