[#update-style]
= Update package imports for style utilities

In version 7, the style utilities have been moved to a separate subpackage:  
`@onecx/angular-utils/style` within the `@onecx/angular-utils` library.

== Update import path

Please update all imports related to micro-frontend and remote component style utilities to use the new package.

.Before
[source,typescript]
----
import { updateStylesForMfeChange } from '@onecx/angular-utils'
----

.After
[source,typescript]
----
import { updateStylesForMfeChange } from '@onecx/angular-utils/style'
----

[IMPORTANT]
====
Besides the import path change, some style helpers were renamed or removed entirely in v7. Update usages as follows:

* `createScopedCss` → renamed to `createApplicationScopedCss`
* `updateStylesForRcRemoval` → removed; use `removeAllRcUsagesFromStyles` or `removeRcUsageFromStyle` as appropriate
* `replaceHtmlWithScope`, `addOriginalCssToStyleElement`, `removeAttributeFromStyle`, `isAppStyle`, `isAppStyleForScope` → removed from the public API with no direct replacement; refactor any usage
====

== Style subpackage public API contents

=== Functions

* `addStyleToHead`
* `createApplicationScopedCss`
* `createCssRequestHeaders`
* `createStyleUsedByMfeRc`
* `fetchAppCss`
* `getAllStylesUsedByKey`
* `getAppStyleByScope`
* `getStyleUsageCount`
* `getStyleUsageCountForRc`
* `isResponseValidCss`
* `isStyleUsedByMfe`
* `removeAllMfeUsagesFromStyles`
* `removeAllRcUsagesFromStyles`
* `removeMfeUsageFromStyle`
* `removeRcUsageFromStyle`
* `replaceRootAndHtmlWithScope`
* `replaceRootWithScope`
* `replaceStyleContent`
* `slotNameToPropertyName`
* `updateStylesForMfeChange`
* `updateStylesForRcCreation`
* `useStyleForMfe`
* `useStyleForRc`

=== Constants

* `dataAppStylesAttribute`
* `dataAppStylesKey`
* `dataMfeStylesAttribute`
* `dataMfeStylesKey`
* `dataRcStylesAttribute`
* `dataRcStylesKey`
* `dataRcStylesStart`
* `dataShellStylesAttribute`
* `dataShellStylesKey`