
= Styles

:idprefix:
:idseparator: -
:scope_at_rule: https://developer.mozilla.org/en-US/docs/Web/CSS/@scope
:scoping: ./scoping.adoc
:style_types: ./style-types.adoc
:primeng_token_variables: ./primeng-token-variables.adoc
:scope_polyfill: ./scope-polyfill.adoc

This document outlines the styles mechanisms available in OneCX, focusing on how styles are structured, applied, and managed. It provides both conceptual and technical insights to help developers and administrators understand how to implement and customize styles effectively. After reading, you should be able to:

- Understand the concept of style isolation in OneCX.
- Use scoped styles and application styles.
- Know how to apply and manage styles at runtime.

[#style-isolation-idea]
== Style Isolation
Style isolation is a concept that aims to address the issue of styles sharing between different Microfrontends on a single page. By design, on a single page there will be at least Shell UI content and the current Microfrontend's content, making it 2 active applications that require different CSS styles for appropriate presentation. With Remote Components, the amount of the active applications grows to larger numbers making it more likely that CSS rules are clashing with each other. This can lead to potential unwanted side effects for the application display.

The style isolation concept assumes that each application needs to set up the required CSS rules for itself and none of them are leaking to other application's content. In OneCX, the style isolation concept has been implemented since version 6.

[#scoped-styles]
=== Scoped Styles
To support the style isolation concept in OneCX, all style sheets (apart from Shell UI's global style sheet) are scoped. A scoped style sheet is a CSS style sheet that contains no global CSS rules but only ones that are utilizing the {scope_at_rule}[CSS @scope at-rule]. This rule ensures that all CSS rules defined in it will be scoped to certain boundaries on a page.

More details on how scoping works in OneCX can be accessed link:{scoping}[here].

[#application-styles]
=== Application Styles
As already mentioned, each application has to take care of its own styles since nothing is declared globally. This is possible by dynamic CSS loading. Whenever a Microfrontend or Remote Component is created, the CSS style sheet of the application they belong to will be loaded on the page. The only requirement for the application is to expose the `styles.css` file.

The `styles.css` file has to be exposed by the application on the remote URL level. As an example, if the remote URL of the Microfrontend is `localhost:4200/deploymentUrl`, the style sheet has to be exposed on the `localhost:4200/deploymentUrl/styles.css` URL.

[#nx-application-styles]
==== NX Application Styles
It's recommended to do the following modification to the `project.json` file to ensure it's exposed correctly (where input is a path to the application styles):

.project.json modification
[source,json]
----
{
    ...
    "styles": [
        {
            "input": "./src/styles.scss",
            "bundleName": "styles",
            "inject": true
        }
    ],
    ...
}
----

[#angular-cli-application-styles]
==== Angular CLI Application Styles
It's recommended to do the following modification to the `package.json` file to ensure it's exposed correctly (where *my-project-name* should be the name of the modified project):

.angular.json modification
[source,json]
----
{
    ...
    "scripts": {
        "postbuild": "mv \"$(find dist/my-project-name -maxdepth 1 -type f -name 'styles.*.css' | head -n 1)\" dist/my-project-name/styles.css",
    }
    ...
}
----

[#component-styles]
==== Component Styles
Component styles are a special case of style sheets that exists in technologies like Angular. In case of Angular, those style sheets are usually scoped by their definition (scoped to the component). Apart from the application styles, those are the other option to define styles for your content.

[#at-rule-scope-support]
==== @scope support
The `@scope` at-rule is not widely supported yet in all browsers. For that reason, a polyfill has been prepared (located in the Shell UI) that automatically takes care of the scoping for all browsers that do not support the rule.

[#technical-details]
== Technical details
Access the technical details for the following topics:

* link:{scoping}[Style scoping details] - how style scoping is used in OneCX to ensure style isolation
* link:{style_types}[Style sheets on the page] - what different style sheets are on a single OneCX page
* link:{primeng_token_variables}[PrimeNG variable overrides] - how application and component style sheets are affected when using PrimeNG design token variables
* link:{scope_polyfill}[@scope polyfill] - details on how the @scope polyfill works
