
= Style Types

:idprefix:
:idseparator: -
:application_styles: ./concept.adoc#application-styles

The goal of this document is to explain style types located on the OneCX page. After reading this document it should be clear what different styles are available on the OneCX page and what their purpose is.

[#overview]
== Overview
In the document head, there are plenty of different style sheets. These style sheets are present for different use-cases and are constructed in several different ways. These style sheets can be split into groups based on their purpose:

* Shell scoped - sheet that should be used only by the shell.
* Application scoped - sheet that should be used only by the respective application.
* Global scoped - sheet that should be available globally on the whole page.
* Legacy - sheet that should be used only by respective content for legacy reasons.
* PrimeNG - sheet that defines PrimeNG CSS rules used by PrimeNG components.

[#style-sheet-list]
== Style Sheet List
There are plenty of style sheets on each page in OneCX. In order to distinguish style elements on the page and reduce the number of HTTP calls, we defined a set of HTML attributes. Below is a list of all possible style sheets on the page:

[cols="1,1,1,3"]
|===
|Purpose |Location |Attribute |Description 

|PrimeNG
|PrimeNG library
|data-primeng-style-id
|Contains CSS (variables or other rules) for PrimeNG components.

|PrimeNG
|Generated based on theme overrides
|data-variable-override-id="scopeId"
|Contains CSS variable overrides for PrimeNG components for a respective scope.

|Application
|Application's component
|None
|Contains CSS for components implemented by the respective application.

|Application
|Application styles (exposed via styles.css)
|data-app-styles="scopeId"
|Contains CSS for the whole application recognized by the scope identifier.

|Global
|Shell UI - splash.scss
|None
|Contains CSS for content for the splash loading screen. Injected into the page via `<link>`.

|Global
|Shell UI - global-styles.scss
|None
|Contains CSS for the whole page. Injected into the page via `<link>`.

|Shell
|Shell UI - shell-styles.scss
|data-shell-styles
|Contains CSS for content for the Shell application.

|Legacy
|Shell UI - portal-layout-styles.scss
|data-portal-layout-styles
|Contains CSS for content that requires portal layout styles legacy CSS rules.

|Legacy
|Shell UI - portal-layout-styles.scss
|data-dynamic-content-portal-layout-styles
|Contains CSS for dynamic content that requires portal layout styles legacy CSS rules.
|=== 

[#primeng]
=== Purpose - PrimeNG
PrimeNG style sheets are constructed by the PrimeNG library and modified by OneCX, and in the case of theme overrides, style sheets are constructed by OneCX completely.

[#global]
=== Purpose - Global
Global style sheets aim to define crucial CSS rules for the whole page to run correctly. Global styles should be updated as *the last option*.

[#shell]
=== Purpose - Shell
Shell is a special case of the application that is not loaded dynamically but hosts other applications. For that reason, a separate specific sheet has been prepared for it.

Shell styles are loaded by the Shell on its initialization.

[#legacy]
=== Purpose - Legacy
In the past (Shell with Angular 18 and libs version 5), Shell UI was injecting a style sheet that was shared between the applications. For that reason, legacy style sheets were prepared. These sheets contain all rules that were previously available in a global fashion. However, they are scoped as well and should be available for only those applications that rely on those global styles being available.

In essence, every application that has libs version 5 and less should require the legacy styles to work properly.

Legacy styles are loaded by the Shell on its initialization.

[#application]
=== Purpose - Application
To style each application, developers should use the component styles available by the respective technology of the application. If those are not available or there are some rules that should be shared between components, each application can expose a style sheet that contains them. The only requirement is that it should be link:{application_styles}[exposed correctly via styles.css file] that will be loaded dynamically by the Shell. This style sheet will be available for that application only and will not be shared with other applications.

[#application-styles-details]
== Application Styles Details
On a single page in OneCX, there can be content originating from multiple different applications:

* Shell UI overlay
* A microfrontend
* Many remote components (from different applications)

Microfrontend and remote components can originate from the same application, and therefore there is no need to load a style sheet every time a new microfrontend or remote component is displayed. The following attributes play a crucial role in reducing the amount of style sheet loading:

* data-app-styles="scopeId" - Marks style sheet as application sheet for the respective scope.
* data-mfe-styles - Marks style sheet as used by the current microfrontend.
* data-slot-$SLOT_NAME-styles - Marks style sheet as used by one of the remote components inside a slot with a name equal to $SLOT_NAME (slot name is a lowercase, '-' separated string).

The application style sheet is loaded only when a new microfrontend or remote component (originating from the respective application) is created. However, before loading happens, it is checked if there is an existing style sheet with the expected data-app-styles attribute. If that's the case, the sheet is not loaded.

* If the style sheet load was initiated by microfrontend creation, it receives the data-mfe-styles attribute.
* If the style sheet load was initiated by remote component creation, it receives the data-slot-$SLOT_NAME-styles attribute.
* In cases where the style sheet already exists, the respective attributes are appended to the appropriate sheet.
* On microfrontend or remote component removal (technically slot removal), the attributes are deleted from the style sheet, and if there are no other usages (no other slot or microfrontend uses the style sheet), it is removed from the DOM.

[#angular-19-plus-applications]
=== Angular 19+ Applications
Angular 19+ applications fully support the style isolation concept in OneCX. Therefore, application styles (exposed via styles.css) are applied to all content originating from the respective application, including microfrontend's content and remote components.

[#apply-angular-18-remote-components]
=== Apply Application Styles to Angular 18 Remote Components
Because of the legacy assumptions in Angular 18 applications, where application styles (exposed via styles.css) are applied only to the microfrontend's content, but not to the remote components originating from the same application, by default, application styles are not active for remote components. There are 2 ways to change this behavior:
* Disable portal layout styles for the remote component by utilizing 4th parameter of bootstrapRemoteComponent method.
* Move required CSS rules from application styles to component styles.